version: '3'

services:
  backend:
    build: ./backend
    ports:
      - "3001:3001"
    volumes: 
      - ./backend:/app
    environment:
      - PORT=3001

  frontend:
    build: ./frontend
    volumes:
      - ./frontend:/frontend
    ports:
      - "3000:3000"

  test:
    build: ./test
    # volumes:
    #   - ./frontend/src:/frontend/src
    ports:
      - "3002:3000"

  reverse-proxy:
    build: ./nginx
    # volumes:
    #   - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
      # - "443:443"
    depends_on:
      - backend
      - frontend
      - test
